# SPDX-FileCopyrightText: 2026 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

snapshot: lts-24.34

packages:
  - .

ghc-options:
  "$locals": -Werror

extra-deps:
  - hledger-lib-1.52
